---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: global-settings
data:
  # mcvlan_static_range: &anchor_ip_mcvlan_static_range
  # 192.168.1.0-192.168.1.63
  CLUSTER_MACVLAN_HA: "1"
  CLUSTER_MACVLAN_PLEX: "2"
  CLUSTER_MACVLAN_CCU: "3"
  CLUSTER_MACVLAN_UNIFI: "4"

  # lb_static_range: &anchor_ip_lb_static_range
  # 192.168.1.128-192.168.1.192
  CLUSTER_LB_INGRESS: "128"
  CLUSTER_LB_CCU: "129"
  CLUSTER_LB_HA: "130"
  CLUSTER_LB_IOBROKER: "131"
  CLUSTER_LB_GITEA: "132"
  CLUSTER_LB_PLEX: "133"
  CLUSTER_LB_OPENVPN: "134"
  CLUSTER_LB_LORAFWD: "135"
  CLUSTER_LB_MOSQUITTO: "136"
  CLUSTER_LB_UNIFI: "137"
