---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
#crds:
#  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.crds.yaml
resources:
  - azuredns-config.enc.yaml
  - default-cert.yaml
  - letsencrypt-clusterissuer-prod.yaml
