apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: botkube-helm-values
  namespace: monitoring
data:
  values.yaml: ENC[AES256_GCM,data:oW60JSiT48ZhyAteLDszp/oN6sUj4z99zPR0wdf4sF/iAN1ZbMC988WZCI3Dvch719HpyNLdQT/Uf6o8z6RCsaaOTJGzWFkPsibiuRRJtg5ncsw4K4eaxnXHmb+e8TvhhhnPXD2MVf9hEtRLo9It9IoB/ijZfcMa//bBTIZi5195gvBBbHkFB9YU6YjxnWUVp2cFK59AXu9YHFFHw0ehgtDmkhLRc+eG4dFDS6qPVx5gR4BZN5RPSzPhY4lM38iRne4kzKVeqt0YZmHecmrsvM2N8a1nnglhd1/PmY858f9Z5LqDYMg7EXpb3znwNimDYxV4944dgFpNHDyhhANN24lEb7Ndrp421BITuqwwMVnH5Ktp,iv:jESZt5u5lehdBLeEgsRB6nRQdzsZ6kkp4eDZypXkeaU=,tag:kaRrSaLSvc9Z7g1nS0TfEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2021-04-12T18:21:12Z"
  mac: ENC[AES256_GCM,data:2pBd4J9OBPZodBh3ufVHEWMqhAz5GVcBIfo1qniPojaJypfLqNNDP7jV/J+aQlMzs/3yvvN7rsSq7lH1Ag2wb8DqvAbckUhhIn/FY2/tSn3P5Bwhgoi7+Rjff+h8fDgEAGavkxdn8YFWcP7oORkZQ0xC527ws6sS3K/IczvCvDY=,iv:yvcUpUDVdf+/JZzurVhS+EzaPTqPrPfE3jEqnd53LW0=,tag:L8pFFfsloRNFU0RntTwc+w==,type:str]
  pgp:
    - created_at: "2021-04-12T18:21:11Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA8oSIqtHvng8AQ//cfsr+ql2/op9X0xUf8FF0KEg+3r8XNTdvPmOZyJhV3UB
        EVfwuUquWypeaL2EDymD/i5ETxpJiv38c9MZJDGWUjsd0ZzVjNtKddD85zUMteCm
        nfqtFu1QeLR8eBhEGKHwftmmpVhHNezEN0u4O3upDCRXSGXLD0SYi4xuKOTpQuT+
        dPG9jcEEoNMjS9OR2Gh8WqdVCiWHOrErmGZ7QkrXXqTJa/V+/PVlfGNQOBhwbIHP
        Y082STqxRMUY+fXFrvvhj8E3djWA08j7BAmigCWrvKIMZtJ6rAi2vBf/reEIWc8P
        +U2dsjk8LO0fRp7alK8IF5CAZmNViWT542Lp+wrbpsjcirinxBRhJi5KwMxk2mv7
        +qjxQFKxnt/B1LPp/gBAvifCyQBIzdOgVTC7lCZU9xIeS20BwX+POwzlH1n8QjD8
        hg58Le7WHcciZ+UV19gQN5VXtH2SkWaSweB6yYLUWO5urj6hEQA11psEOmXXkXB1
        G9r90uOywSDrHcyzs5arOUrpjhhXsAHnrw6lUM0M+KXRkilwTwZGZKfKJTGKO/I8
        6lszRBG0zoWtfTSUAeWG6eg+ykloeCwXB+qCCLeZzREqGVLgzopD1xBNFwdeY+mw
        j8Rh4ojAhlsBGFM9JxQuge4HPqANRh0LZ/NHjQlOHGzdLcpYwS7DceWRhTO2qmDS
        XgHsBzJJlKt7Emx2vkO0Ugokj/TGiZhvTygeHHO3aiAnBFTxBzkJd5Ou1ixo8HbR
        /XkXtNhQJ42znXlEXUYYFfeK1OyCWF+E4uGHsLPbIZOg2AtPoS/FVAu812Thhks=
        =tDne
        -----END PGP MESSAGE-----
      fp: DA8002060402EC39B195451D5CED80362B5A4EF2
    - created_at: "2021-04-12T18:21:11Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA3VNo8GgxHGmARAAtah78J/hp65UIpqu+rHViG23weeypUXc8NQJA7rMZuCp
        +EF/TvYfKZWN+TSczfNI++r3jAmweZhTkHCRJ6FjH80B8HcY1AsjHqW2AFBzeqx2
        7S/d+8BSCoPEtL0JFQpzd03DzaMpReceuIuFsCatgoKuDkxHyURY9rVfjQaOcb8c
        zENdWHobQw8qcKvZx9TYXp+QxzFHVGb8BazQfqgNpKYQ18Ba1EPgsLMXIh1Iq+H7
        1DxNT6/17Jp+D7QY/ou7Xp3ni2UX9aVceZ9pYwdzecmj+tP+caRE1Nne2kpTBTXI
        HmxF3u5lijGAztpL0n4gS/fOIQxiUPhO5SPotyn4RpzVG+iaFr2+ZMdXC6Uqtues
        CGf37MerUMjtDfnZNblhRbEoZ8E/fZ0nbG2gPklUzFkGtmrGx7FUhzHV/zNeh0ve
        eJlhUbOKEEM8IijagPpGyDyliSFfkfzJ6X1zs5La0VFZ1Oe2X7PR5BTcjXVwzblR
        MKPEQhJN2pvIESs9fydoUWP6f4JAuytq7CGoY3bZNbkQiAHzt+MsPjCTaDHpyARq
        oxLwGF2kwFsv51pvpXsRhb/aTEB+aB0NcJsTQxLXADtaU1oSss0zzau24+UuxcDp
        +sDwvTIo3FRywFAkgcMTMs97YgGL/EaXmK0NNwz3+JzbgREb09kjXiSROC9aYYHS
        XgF9gy7YeR7BAe6r5QD0B2XspVGLb4D9R16fb/yfsBZRJLP6Mf0/hNt2lCW9/CY3
        xrVuhV8zPruHsUjgHWuUXdWWrMAXu6ZDOLd4wxpNWoY3A2/it1wc33/1ZcDad0s=
        =O6cj
        -----END PGP MESSAGE-----
      fp: 8E249DB719CB920293DDD70F8B791C2579360E5A
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
