---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  #VALUES DIFFERENT PROD - STAGING
  CLUSTER_ENV: "prod"
  CLUSTER_DOMAIN: rvprobs.com
  CLUSTER_DOMAIN_CERT: prod-wildcard-rvprobs-com-tls
  CLUSTER_EXTERNAL_SUBNET_PREFIX: "192.168.1"
  CLUSTER_LB_RANGE: "192.168.1.128-192.168.1.192"

  CLUSTER_DB_VERSION: "13"
  CLUSTER_DB_NODE_0: server.rvprobs.com
  CLUSTER_DB_NODE_1: server2.rvprobs.com
  CLUSTER_DB_BACKUP_PREFIX: "backup/db"
