---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator-ui/
      chart: postgres-operator-ui
      version: v1.6.1
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-ui
        namespace: flux-system
      interval: 5m
  # https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.${CLUSTER_DOMAIN}/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.${CLUSTER_DOMAIN}/start?rd=$scheme://$host$request_uri"
      ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
      - host: "postgres-operator.${CLUSTER_DOMAIN}"
        paths: [""]
      tls:
      - hosts:
        - "postgres-operator.${CLUSTER_DOMAIN}"
