---
all:
  hosts:
    rvk8s:
      hostname: rvk8s.rvprobs.com
      ansible_host: 10.9.18.199


controlplane:
  hosts:
    rvk8s:
      hostname: rvk8s.rvprobs.com
      ansible_host: 10.9.18.199

nodes:
  hosts:
    rvk8s:
      hostname: rvk8s.rvprobs.com
      ansible_host: 10.9.18.199
#     node-1:
#       hostname: node-1.holthome.net
#       ansible_host: node-1.holthome.net
#     node-2:
#       hostname: node-2.holthome.net
#       ansible_host: node-2.holthome.net
#     node-3:
#       hostname: node-3.holthome.net
#       ansible_host: node-3.holthome.net

# workers:
#   hosts:
#     node-0:
#       hostname: node-0.holthome.net
#       ansible_host: node-0.holthome.net
#     node-1:
#       hostname: node-1.holthome.net
#       ansible_host: node-1.holthome.net
#     node-2:
#       hostname: node-2.holthome.net
#       ansible_host: node-2.holthome.net
#     node-3:
#       hostname: node-3.holthome.net
#       ansible_host: node-3.holthome.net

masters:
  hosts:
    rvk8s:
      hostname: rvk8s.rvprobs.com
      ansible_host: 10.9.18.199

cluster:
  children:
    controlplane:
    # nodes:

k8s:
  children:
    masters:
    # workers:

vault:
  hosts:
    localhost:
      ansible_connection: local
